CREATE TABLE aiw_ai_model_call_audit (
    biz_id VARCHAR(64) PRIMARY KEY COMMENT '业务唯一标识',
    call_id VARCHAR(64) NOT NULL COMMENT '单次模型调用追踪标识',
    operation_code VARCHAR(96) NOT NULL COMMENT '业务操作编码',
    call_status VARCHAR(32) NOT NULL COMMENT 'STARTED/SUCCEEDED/FAILED/BLOCKED',
    provider_code VARCHAR(64) NOT NULL COMMENT '模型提供方编码',
    model_code VARCHAR(96) NOT NULL COMMENT '模型稳定编码',
    model_version VARCHAR(96) NOT NULL COMMENT '模型版本',
    remote_model VARCHAR(128) NULL COMMENT '供应商侧模型名称',
    endpoint VARCHAR(512) NULL COMMENT '脱敏后的调用端点',
    http_method VARCHAR(16) NOT NULL DEFAULT 'POST' COMMENT 'HTTP 方法',
    http_status INT NULL COMMENT '远端 HTTP 状态',
    duration_ms BIGINT NULL COMMENT '调用耗时毫秒',
    system_prompt_hash VARCHAR(128) NULL COMMENT '系统提示词 SHA-256',
    user_prompt_hash VARCHAR(128) NULL COMMENT '用户提示词 SHA-256',
    response_hash VARCHAR(128) NULL COMMENT '模型输出 SHA-256',
    request_preview TEXT NULL COMMENT '脱敏截断后的输入预览',
    response_preview TEXT NULL COMMENT '脱敏截断后的输出预览',
    input_summary JSON NULL COMMENT '结构化输入摘要',
    output_summary JSON NULL COMMENT '结构化输出摘要',
    business_type VARCHAR(64) NULL COMMENT '关联业务类型',
    business_biz_id VARCHAR(64) NULL COMMENT '关联业务对象标识',
    business_label VARCHAR(255) NULL COMMENT '业务展示名称',
    task_code VARCHAR(128) NULL COMMENT '任务编码',
    event_id VARCHAR(64) NULL COMMENT '任务事件标识',
    run_biz_id VARCHAR(64) NULL COMMENT '闭环运行标识',
    run_no VARCHAR(64) NULL COMMENT '闭环运行号',
    report_biz_id VARCHAR(64) NULL COMMENT '投资报告标识',
    prompt_biz_id VARCHAR(64) NULL COMMENT 'Prompt 标识',
    prompt_code VARCHAR(128) NULL COMMENT 'Prompt 编码',
    prompt_version VARCHAR(96) NULL COMMENT 'Prompt 版本',
    skill_biz_id VARCHAR(64) NULL COMMENT 'AI Skill 标识',
    skill_code VARCHAR(128) NULL COMMENT 'AI Skill 编码',
    skill_version VARCHAR(96) NULL COMMENT 'AI Skill 版本',
    model_skill_binding_biz_id VARCHAR(64) NULL COMMENT '模型 Skill 绑定标识',
    scenario_code VARCHAR(96) NULL COMMENT '业务场景编码',
    environment VARCHAR(64) NULL COMMENT '运行环境',
    error_code VARCHAR(96) NULL COMMENT '错误编码',
    error_message VARCHAR(1024) NULL COMMENT '错误摘要',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    updated_at DATETIME NOT NULL COMMENT '更新时间',
    UNIQUE KEY uk_aiw_ai_model_call_audit_call (call_id),
    KEY idx_aiw_ai_model_call_audit_created (created_at),
    KEY idx_aiw_ai_model_call_audit_model (model_code, model_version, created_at),
    KEY idx_aiw_ai_model_call_audit_business (business_type, business_biz_id),
    KEY idx_aiw_ai_model_call_audit_task (task_code, event_id),
    KEY idx_aiw_ai_model_call_audit_run (run_biz_id, run_no),
    KEY idx_aiw_ai_model_call_audit_prompt (prompt_code, prompt_version),
    KEY idx_aiw_ai_model_call_audit_skill (skill_code, skill_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI模型调用审计流水';
